import "../css/globals.css";
import { Inter } from "next/font/google";
import { Menu, Footer } from "@/UI";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <head>
        {/* <link rel="icon" href="../logo/favicon.ico" sizes="any" /> */}
        <script src="//code.jivo.ru/widget/yZuDqsMQDU" async></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                        (function (m, e, t, r, i, k, a) {
                          m[i] =
                            m[i] ||
                            function () {
                              (m[i].a = m[i].a || []).push(arguments);
                            };
                          var z = null;
                          m[i].l = 1 * new Date();
                          for (var j = 0; j < document.scripts.length; j++) {
                            if (document.scripts[j].src === r) {
                              return;
                            }
                          }
                          (k = e.createElement(t)),
                            (a = e.getElementsByTagName(t)[0]),
                            (k.async = 1),
                            (k.src = r),
                            a.parentNode.insertBefore(k, a);
                        })(window, document, 'script', 'https://mc.yandex.ru/metrika/tag.js', 'ym');

                        ym(90256919, 'init', {
                          clickmap: true,
                          trackLinks: true,
                          accurateTrackBounce: true,
                          webvisor: true
                        })
                    `,
          }}
        />
        <noscript>
          <div>
            <img
              src="https://mc.yandex.ru/watch/90256919"
              style={{ position: "absolute", left: "-9999px" }}
              alt=""
            />
          </div>
        </noscript>
      </head>

      <body className={inter.className}>
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
